site_name: CameraDeamon Documentation
pages:
- About: index.md
- Dependencies and Environment: env.md
- Basic Camera Operation: basic.md
- Communication: communication.md
- Deamonization: deamonization.md
- Logging: logging.md
- Multi Camera: multi.md
- Output / Analysis: output.md
theme: readthedocs
repo_url: https://github.com/motioniq/CameraDeamon
repo_name: CameraDeamon
site_author: Selwyn-Lloyd McPherson